build_from:
  aarch64: "node:14"
  amd64: "node:14"
  armhf: "node:14"
  armv7: "node:14"
  i386: "node:14"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Android Icon"
  org.opencontainers.image.description: "Retrieve the icon of an Android app"
  org.opencontainers.image.source: "https://github.com/lageorgem/home-assistant-addon-android-icon"
  org.opencontainers.image.licenses: "Apache License 2.0"