name: android-icon
version: '1.0'
slug: android_icon
description: Retrieve the icon of an android app
url: "https://github.com/lageorgem/home-assistant-addon-android-icon/"
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: services
boot: auto
hassio_api: false
homeassistant_api: false
ingress: true
ingress_port: 1337
ingress_entry: app
host_network: true
options: {}
schema: {}
webui: http://[HOST]:[PORT:1337]
